package com.muzin.mu.zin.entity.notification;

public enum NotificationType {
    RESERVATION_REQUESTED,
    RESERVATION_CONFIRMED,
    RESERVATION_REJECTED,
    RESERVATION_COMPLETION_PENDING,
    RESERVATION_COMPLETED,
    RESERVATION_CANCELED_BY_USER,
    RESERVATION_CANCELED_BY_ARTIST
    // 추후 NEW_MESSAGE, REVIEW_CREATED 등 추가 예정
}
